---
title: "Reading and processing data for YOURPROJECTNAME"
date: "`r Sys.Date()`"
author: "YOURNAME"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Step 0: Loading packages and annotation file
```{r}
# Recording time 
begin_time <- Sys.time()

# Loading R packages 
library(here)

# Reading annotation file 
documents_folder <- paste0(here(),"/documents/annotation/")
annotation <- read.csv(paste0(documents_folder, "/annotation.csv"),
                              stringsAsFactors = FALSE)
annotation[[1]] <- tolower(annotation[[1]]) 
rownames(annotation) <- annotation[[1]]

# Loading functions
source(here("R/01-data-processing/00_functions.R"))
```

# Step 1: Loading data
```{r}
# You might want to use this to speed up the initial loading of data
data_folder <- paste0(here(),"/data/raw/")
data <-
  data.table::fread(
    paste0(data_folder, "YOURDATA.csv"),
    stringsAsFactors = FALSE,
    data.table = FALSE
  )

```




# Saving processed data
```{r}

# Time it took to perform the computations 
end_time <- Sys.time()
time_it_took <- end_time - begin_time
date_saved <- end_time
system_info <- Sys.info()  
session_info <- sessionInfo()

# Saving results
to_save <- c("data",
             "annotation")
file <- paste0(here(), "/data/cleaned/read_data.RData")
to_save <- c(to_save,
             "time_it_took",
             "date_saved",
             "system_info",
             "session_info")
save(list = to_save,
     file = file)
```

# R session information
```{r}

x <- as.numeric(unclass(time_it_took))
unit <- attr(time_it_took, "units")
```

It took `r round_n.ade(x, 2)` `r unit` for all analyses to run.
```{r, comment="", results='markup'}

sessionInfo()
rm(list = ls())
```
